### ISSUE TITLE
re: Import pangolin.gfx in game_screen.bmx

### ISSUE THREAD

**Issue by braxtonrivers** [Sodaware/pangolin.mod#1]
Hi Phil,

I really like your coding style, it is very clean and easy to read, I only just happened upon your blitzmax modules,
when I also noticed that the missing pangolin.gfx could contain the type for AbstractRenderRequest.

Thanks in advance

**Comment by Sodaware** [comment]
Thank you for the kind words! I've pushed up some more code, including the missing AbstractRenderRequest type.

Cheers,
Phil
